name: oprecnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - torchvision=0.13.1
  - pytorch=1.12.1
  - cpuonly=2.0
  # - torchaudio=0.10.0
  - ipykernel=6.15.2
  - scipy=1.9.1
  - sympy=1.10.1
  - matplotlib=3.5.3
